# Generated by Django 3.2.2 on 2022-07-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.IntegerField(default='1')),
                ('court_name', models.CharField(default='court', max_length=50)),
            ],
        ),
    ]
