# Generated by Django 3.2.2 on 2022-07-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='court_image',
            field=models.ImageField(default='', upload_to='display/img/court_img'),
        ),
    ]
