# Generated by Django 3.2.2 on 2022-07-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_court_court_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='court_image2',
            field=models.ImageField(default='', upload_to='display/img/court_img'),
        ),
    ]
