# Generated by Django 3.2.2 on 2022-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0004_court_court_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_image',
            field=models.ImageField(default='', upload_to='court/img/court_img'),
        ),
        migrations.AlterField(
            model_name='court',
            name='court_image2',
            field=models.ImageField(default='', upload_to='court/img/court_img'),
        ),
    ]
